server:
  port: 8083

spring:
  application:
    name: ai-service
    data:
      mongodb:
        uri: mongodb://localhost:27017/recommendation_DB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


