server:
  port: 8083

spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/recommendation_DB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      name: fitness_exchange
    routing:
      key: activity.tracking

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


      gemini:
        api:
          url:${GEMINI_API_URL}
            key:${GEMINI_API_KEY}